- include: "{{ansible_os_family}}.yml"

- name: Add Kafka User
  user:
    name: kafka
    shell: /usr/sbin/nologin
    home: /opt/kafka
    create_home: no

- name: Download Kafka
  unarchive:
    src: "{{kafka_meta[kafka_version].download_url}}"
    dest: /opt/
    remote_src: yes
    owner: kafka
    group: kafka
    
- shell: mv /opt/kafka_* /opt/kafka

- name: Setting Environment
  shell: echo 'export PATH="$PATH:/opt/kafka/bin"' >> /etc/profile

- name: Configuration Zookeeper 
  copy:
    src: zookeeper.properties
    dest: /opt/kafka/config
    owner: kafka 
    group: kafka

- name: Configuration Kafka
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: 'log.dirs=/tmp/kafka-logs'
    line: 'log.dirs=/opt/kafka/kafka-logs'
    owner: kafka 
    group: kafka

- name: Configuration Zookeeper Server
  copy:
    src: zookeeper.service
    dest: /lib/systemd/system/

- name: Configuration Kafka Server
  copy:
    src: kafka.service
    dest: /lib/systemd/system/

- name: Start Zookeeper
  service:
    name: zookeeper
    state: started
    enabled: yes

- name: Start kafka
  service:
    name: kafka
    state: started
    enabled: yes

- name: Setting Owner and  Group
  shell: chown -R kafka. /opt/kafka


# add soft link
- name: Add soft link 
  shell: |
    ln -sf /opt/kafka /data
    ln -sf /opt/kafka/log /data/logs

# display version of components
- name: Get kafka version
  shell: sudo sh -c " ls /opt/kafka/libs | grep kafka_ 1>> /data/logs/install_version.txt"

- name: Check kafka Service
  shell: systemctl status kafka | grep Active*
  register: check_kafka_service
  notify: check_kafka_service
